with uinamespace do {
	CTRL_INGAME_HEADER = controlNull;
	CTRL_SPECTATOR_PLAYERLIST = []; 
	DATA_SPECTATOR_PLAYERNAMES = [];
	DATA_SPECTATOR_PLAYERDATA = [];
	CTRL_SPECTATOR_ISRUNNING = false;
	THREAD_SPECTATOR_START = scriptNull;
};